import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
        <section className="mx-auto container grid auto-rows-auto justify-items-center min-h-screen sm:p-1 font-[family-name:var(--font-geist-sans)]">
            <Header/>
            {children}
            <Footer/>
        </section>
  );
}
